import mongoose from "mongoose"
import dotenv from "dotenv"
import fs from "fs"
import MED from "./appModele.js"

dotenv.config({ path: "./.env" })

// Brand names + aliases for all 236 medications
const enrichmentData = {
  "Atorvastatin": { brands: ["Tahor", "Lipitor", "Torvast", "Cardyl", "Sortis"], aliases: ["atorvastatine", "atorvastatin"] },
  "Metformin": { brands: ["Glucophage", "Metforal", "Stagid", "Glucinan", "Diaformin"], aliases: ["metformine", "metformin"] },
  "Levothyroxine": { brands: ["Levothyrox", "Synthroid", "Euthyrox", "Thyrax", "L-Thyroxin"], aliases: ["levothyroxine", "lévothyroxine", "l-thyroxine"] },
  "Lisinopril": { brands: ["Zestril", "Prinivil", "Lisipril", "Alapril", "Novatec"], aliases: ["lisinopril", "lisinoprill"] },
  "Amlodipine": { brands: ["Amlor", "Norvasc", "Istin", "Caldine"], aliases: ["amlodipine", "amlodipina"] },
  "Metoprolol": { brands: ["Lopressor", "Toprol", "Seloken", "Betaloc", "Metohexal"], aliases: ["metoprolol", "métoprolol"] },
  "Albuterol": { brands: ["Ventolin", "Salbutol", "Airomir", "Proventil", "Salamol"], aliases: ["salbutamol", "albuterol", "salbutamole"] },
  "Losartan": { brands: ["Cozaar", "Lortaan", "Losartic", "Losacar"], aliases: ["losartan", "losartane"] },
  "Gabapentin": { brands: ["Neurontin", "Gralise", "Gabarone", "Gabator", "Nepatic"], aliases: ["gabapentin", "gabapentine"] },
  "Omeprazole": { brands: ["Mopral", "Losec", "Prilosec", "Zoltum", "Omepral"], aliases: ["omeprazol", "omeprazole"] },
  "Sertraline": { brands: ["Zoloft", "Lustral", "Serlain", "Asentra"], aliases: ["sertraline", "sertralina"] },
  "Rosuvastatin": { brands: ["Crestor", "Rosulip", "Provisacor", "Rosuvast"], aliases: ["rosuvastatine", "rosuvastatin"] },
  "Pantoprazole": { brands: ["Eupantol", "Pantoloc", "Protonix", "Inipomp", "Pantecta"], aliases: ["pantoprazol", "pantoprazole"] },
  "Escitalopram": { brands: ["Lexapro", "Cipralex", "Seroplex", "Esertia", "Lexamil"], aliases: ["escitalopram", "escitaloprame"] },
  "Amphetamine-Aspartate-Amphetamine-Dextroamphetamine": { brands: ["Adderall", "Adderall XR"], aliases: ["amphetamine salts", "mixed amphetamine"] },
  "Hydrochlorothiazide": { brands: ["Esidrex", "HydroDIURIL", "Microzide", "Oretic"], aliases: ["hydrochlorothiazide", "HCTZ", "hydrochlorothiazid"] },
  "Bupropion": { brands: ["Wellbutrin", "Zyban", "Aplenzin"], aliases: ["bupropion", "bupropione"] },
  "Fluoxetine": { brands: ["Prozac", "Fluctine", "Sarafem", "Fluox", "Fontex"], aliases: ["fluoxetine", "fluoxétine"] },
  "Semaglutide": { brands: ["Ozempic", "Wegovy", "Rybelsus"], aliases: ["semaglutide", "sémaglutide"] },
  "Montelukast": { brands: ["Singulair", "Montair", "Lukast", "Monkasta"], aliases: ["montelukast", "montelukaste"] },
  "Trazodone": { brands: ["Trittico", "Desyrel", "Oleptro", "Molipaxin"], aliases: ["trazodone", "trazodona"] },
  "Simvastatin": { brands: ["Zocor", "Lodales", "Simvacor", "Lipovas"], aliases: ["simvastatine", "simvastatin"] },
  "Amoxicillin": { brands: ["Clamoxyl", "Amoxil", "Trimox", "Flemoxin", "Ospamox"], aliases: ["amoxicilin", "amoxycillin", "amoxiciline"] },
  "Tamsulosin": { brands: ["Omix", "Flomax", "Josir", "Mecir"], aliases: ["tamsulosin", "tamsulosine"] },
  "Acetaminophen; Hydrocodone": { brands: ["Vicodin", "Norco", "Lortab", "Zydone"], aliases: ["hydrocodone acetaminophen", "paracetamol hydrocodone"] },
  "Fluticasone": { brands: ["Flixotide", "Flonase", "Flovent", "Cutivate", "Flixonase"], aliases: ["fluticasone", "fluticasona"] },
  "Meloxicam": { brands: ["Mobic", "Movalis", "Recoxa", "Melox"], aliases: ["meloxicam", "meloxicame"] },
  "Apixaban": { brands: ["Eliquis"], aliases: ["apixaban", "apixabane"] },
  "Furosemide": { brands: ["Lasilix", "Lasix", "Frusenex", "Frusid"], aliases: ["furosemide", "frusemide", "furosémide"] },
  "Insulin Glargine": { brands: ["Lantus", "Toujeo", "Basaglar", "Abasaglar"], aliases: ["insulin glargine", "glargine", "insuline glargine"] },
  "Duloxetine": { brands: ["Cymbalta", "Yentreve", "Ariclaim", "Xeristar"], aliases: ["duloxetine", "duloxétine"] },
  "Ibuprofen": { brands: ["Advil", "Nurofen", "Brufen", "Ibuprom", "Dolofen"], aliases: ["ibuprofene", "ibuprofène"] },
  "Famotidine": { brands: ["Pepcid", "Famodil", "Famosan", "Quamatel"], aliases: ["famotidine", "famotidina"] },
  "Empagliflozin": { brands: ["Jardiance"], aliases: ["empagliflozin", "empagliflozine"] },
  "Carvedilol": { brands: ["Kredex", "Coreg", "Dilatrend", "Eucardic"], aliases: ["carvedilol", "carvedilole"] },
  "Tramadol": { brands: ["Tramal", "Topalgic", "Contramal", "Zydol", "Adolonta"], aliases: ["tramadol", "tramadole"] },
  "Alprazolam": { brands: ["Xanax", "Tranax", "Niravam", "Alprax"], aliases: ["alprazolam"] },
  "Prednisone": { brands: ["Cortancyl", "Deltasone", "Sterapred", "Orasone"], aliases: ["prednisone"] },
  "Hydroxyzine": { brands: ["Atarax", "Vistaril", "Ucerax"], aliases: ["hydroxyzine", "hydroxyzina"] },
  "Buspirone": { brands: ["Buspar", "Buspimen", "Narol", "Anxiron"], aliases: ["buspirone", "buspirona"] },
  "Clopidogrel": { brands: ["Plavix", "Clopivas", "Duoplavin", "Zyllt"], aliases: ["clopidogrel"] },
  "Glipizide": { brands: ["Minidiab", "Glucotrol", "Glibenese"], aliases: ["glipizide", "glipizida"] },
  "Citalopram": { brands: ["Seropram", "Celexa", "Cipramil"], aliases: ["citalopram", "citaloprame"] },
  "Potassium Chloride": { brands: ["Kalinor", "Slow-K", "Kaleorid", "Diffu-K"], aliases: ["potassium chloride", "KCl", "chlorure de potassium"] },
  "Allopurinol": { brands: ["Zyloric", "Zyloprim", "Allohexal", "Milurit"], aliases: ["allopurinol", "allopurinole"] },
  "Aspirin": { brands: ["Aspegic", "Kardegic", "Aspirin", "Cardiprin", "Aspro"], aliases: ["aspirine", "acide acetylsalicylique", "ASA"] },
  "Cyclobenzaprine": { brands: ["Flexeril", "Amrix", "Fexmid"], aliases: ["cyclobenzaprine"] },
  "Ergocalciferol (Vitamin D)": { brands: ["Sterogyl", "Drisdol", "Calciferol", "Vitamine D2"], aliases: ["ergocalciferol", "vitamin D2", "vitamine D"] },
  "Oxycodone": { brands: ["OxyContin", "Oxynorm", "Targinact", "Percocet"], aliases: ["oxycodone", "oxycodona"] },
  "Methylphenidate": { brands: ["Ritalin", "Concerta", "Medikinet", "Rubifen"], aliases: ["methylphenidate", "méthylphénidate"] },
  "Venlafaxine": { brands: ["Effexor", "Efexor", "Venlalic", "Alventa"], aliases: ["venlafaxine", "venlafaxina"] },
  "Warfarin": { brands: ["Coumadine", "Coumadin", "Marevan", "Jantoven"], aliases: ["warfarin", "warfarine"] },
  "Spironolactone": { brands: ["Aldactone", "Spirono", "Verospiron"], aliases: ["spironolactone"] },
  "Clonazepam": { brands: ["Rivotril", "Klonopin", "Ravotril", "Clonapam"], aliases: ["clonazepam", "clonazepame"] },
  "Propranolol": { brands: ["Avlocardyl", "Inderal", "Hemangiol", "Propranur"], aliases: ["propranolol"] },
  "Diazepam": { brands: ["Valium", "Stesolid", "Diazemuls", "Antenex"], aliases: ["diazepam", "diazepame"] },
  "Zolpidem": { brands: ["Stilnox", "Ambien", "Edluar", "Zoldem"], aliases: ["zolpidem"] },
  "Mirtazapine": { brands: ["Remeron", "Zispin", "Mirtaz", "Avanza"], aliases: ["mirtazapine"] },
  "Paroxetine": { brands: ["Deroxat", "Paxil", "Seroxat", "Aropax"], aliases: ["paroxetine", "paroxétine"] },
  "Donepezil": { brands: ["Aricept", "Memac", "Yasnal"], aliases: ["donepezil", "donépézil"] },
  "Memantine": { brands: ["Ebixa", "Namenda", "Axura", "Maruxa"], aliases: ["memantine", "mémantine"] },
  "Quetiapine": { brands: ["Seroquel", "Ketipinor", "Nantarid", "Kventiax"], aliases: ["quetiapine", "quétiapine"] },
  "Olanzapine": { brands: ["Zyprexa", "Zalasta", "Rexapin"], aliases: ["olanzapine", "olanzapina"] },
  "Risperidone": { brands: ["Risperdal", "Rispolept", "Belivon", "Ridal"], aliases: ["risperidone", "risperidona"] },
  "Aripiprazole": { brands: ["Abilify", "Arip", "Aristada"], aliases: ["aripiprazole", "aripiprazola"] },
  "Lamotrigine": { brands: ["Lamictal", "Lamitor", "Labileno", "Lamigin"], aliases: ["lamotrigine", "lamotrigina"] },
  "Divalproex Sodium": { brands: ["Depakote", "Depakine", "Epilim", "Valpakine"], aliases: ["divalproex", "valproate", "acide valproique"] },
  "Carbamazepine": { brands: ["Tegretol", "Carbalex", "Timonil", "Neurotol"], aliases: ["carbamazepine", "carbamazépine"] },
  "Levetiracetam": { brands: ["Keppra", "Levroxa", "Elepsia", "Matever"], aliases: ["levetiracetam", "lévétiracétam"] },
  "Topiramate": { brands: ["Epitomax", "Topamax", "Topamac"], aliases: ["topiramate", "topiramato"] },
  "Pregabalin": { brands: ["Lyrica", "Alzain", "Rewisca"], aliases: ["pregabalin", "prégabaline"] },
  "Baclofen": { brands: ["Lioresal", "Kemstro", "Liofen"], aliases: ["baclofen", "baclofene"] },
  "Tizanidine": { brands: ["Sirdalud", "Zanaflex", "Tizan"], aliases: ["tizanidine", "tizanidina"] },
  "Methocarbamol": { brands: ["Robaxin", "Ortoton", "Lumirelax"], aliases: ["methocarbamol"] },
  "Ondansetron": { brands: ["Zophren", "Zofran", "Emeset"], aliases: ["ondansetron", "ondansétron"] },
  "Promethazine": { brands: ["Phenergan", "Promethegan", "Romergan", "Avomine"], aliases: ["promethazine", "prométhazine"] },
  "Metoclopramide": { brands: ["Primperan", "Reglan", "Maxolon", "Plasil"], aliases: ["metoclopramide", "métoclopramide"] },
  "Diphenoxylate-Atropine": { brands: ["Lomotil", "Lomocot"], aliases: ["diphenoxylate atropine"] },
  "Loperamide": { brands: ["Imodium", "Arret", "Lopex", "Imosec"], aliases: ["loperamide", "lopéramide"] },
  "Polyethylene Glycol": { brands: ["Forlax", "Movicol", "MiraLax", "Macrogol"], aliases: ["PEG", "macrogol"] },
  "Docusate": { brands: ["Colace", "Norgalax"], aliases: ["docusate"] },
  "Senna": { brands: ["Senokot", "Ex-Lax", "Pursennide", "Bekunis"], aliases: ["senna", "sennoside", "sené"] },
  "Bisacodyl": { brands: ["Dulcolax", "Contalax", "Laxbene", "Stadalax"], aliases: ["bisacodyl", "bisacodyle"] },
  "Nitroglycerin": { brands: ["Natispray", "Nitrostat", "Nitrolingual", "Minitran"], aliases: ["nitroglycerin", "nitroglycérine", "trinitrine", "GTN"] },
  "Isosorbide Mononitrate": { brands: ["Monicor", "Imdur", "Ismo", "Elantan"], aliases: ["isosorbide mononitrate", "ISMN"] },
  "Digoxin": { brands: ["Digoxine", "Lanoxin", "Digitek"], aliases: ["digoxin", "digoxine"] },
  "Clonidine": { brands: ["Catapressan", "Catapres", "Kapvay", "Dixarit"], aliases: ["clonidine", "clonidina"] },
  "Doxazosin": { brands: ["Cardura", "Zoxan", "Alfadil"], aliases: ["doxazosin", "doxazosine"] },
  "Terazosin": { brands: ["Hytrin", "Dysalfa", "Vicard"], aliases: ["terazosin", "terazosine"] },
  "Finasteride": { brands: ["Propecia", "Proscar", "Chibro-Proscar", "Finastid"], aliases: ["finasteride", "finastéride"] },
  "Dutasteride": { brands: ["Avodart", "Avolve", "Dutagen"], aliases: ["dutasteride", "dutastéride"] },
  "Sildenafil": { brands: ["Viagra", "Revatio", "Silvasta", "Vizarsin"], aliases: ["sildenafil"] },
  "Tadalafil": { brands: ["Cialis", "Adcirca", "Alyq"], aliases: ["tadalafil", "tadalafilo"] },
  "Vardenafil": { brands: ["Levitra", "Vivanza", "Staxyn"], aliases: ["vardenafil"] },
  "Estradiol": { brands: ["Oestrogel", "Estraderm", "Climara", "Vivelledot"], aliases: ["estradiol", "oestradiol"] },
  "Conjugated Estrogens": { brands: ["Premarin", "Presomen", "Climopax"], aliases: ["conjugated estrogens", "oestrogènes conjugués"] },
  "Medroxyprogesterone": { brands: ["Depo-Provera", "Provera", "Farlutal"], aliases: ["medroxyprogesterone", "MPA"] },
  "Norethindrone": { brands: ["Primolut", "Micronor", "Aygestin", "Norlutate"], aliases: ["norethindrone", "norethisterone"] },
  "Drospirenone-Ethinyl Estradiol": { brands: ["Yasmin", "Yaz", "Jasminelle", "Drospibel"], aliases: ["drospirenone ethinylestradiol", "yasmin"] },
  "Etonogestrel": { brands: ["Nexplanon", "Implanon", "Nuvaring"], aliases: ["etonogestrel", "étonogestrel"] },
  "Levonorgestrel": { brands: ["Norlevo", "Plan B", "Mirena", "Jadelle"], aliases: ["levonorgestrel", "lévonorgestrel"] },
  "Prednisolone": { brands: ["Solupred", "Hydrocortancyl", "Predsol", "Deltacortril"], aliases: ["prednisolone", "prednisolon"] },
  "Methylprednisolone": { brands: ["Medrol", "Solumedrol", "Urbason", "Depomedrol"], aliases: ["methylprednisolone"] },
  "Hydrocortisone": { brands: ["Hydrocortisone", "Solu-Cortef", "Efcortesol"], aliases: ["hydrocortisone", "cortisol"] },
  "Betamethasone": { brands: ["Celestone", "Betnesol", "Diprosone", "Betnovate"], aliases: ["betamethasone", "bétaméthasone"] },
  "Triamcinolone": { brands: ["Kenacort", "Kenalog", "Ledercort"], aliases: ["triamcinolone", "triamcinolona"] },
  "Clobetasol": { brands: ["Dermoval", "Temovate", "Clarelux", "Clobex"], aliases: ["clobetasol", "clobetasole"] },
  "Mometasone": { brands: ["Nasonex", "Elocom", "Asmanex", "Elosalic"], aliases: ["mometasone", "mométasone"] },
  "Azithromycin": { brands: ["Zithromax", "Azadose", "Azitro", "Sumamed"], aliases: ["azithromycine", "azitromicina"] },
  "Cephalexin": { brands: ["Keflex", "Ospexin", "Pyassan", "Ceforal"], aliases: ["cephalexin", "cefalexin", "céfalexine"] },
  "Doxycycline": { brands: ["Vibramycin", "Doxyne", "Tolexine", "Doxylag"], aliases: ["doxycycline", "doxiciclina"] },
  "Ciprofloxacin": { brands: ["Cipro", "Ciflox", "Uniflox", "Bacquinor"], aliases: ["ciprofloxacine", "ciprofloxacin"] },
  "Levofloxacin": { brands: ["Tavanic", "Levaquin", "Quixin"], aliases: ["levofloxacin", "lévofloxacine"] },
  "Sulfamethoxazole-Trimethoprim": { brands: ["Bactrim", "Septra", "Cotrimoxazole", "Eusaprim"], aliases: ["cotrimoxazole", "SMX-TMP", "trimethoprim sulfamethoxazole"] },
  "Nitrofurantoin": { brands: ["Furadantine", "Macrobid", "Nitrofur", "Uvamin"], aliases: ["nitrofurantoin", "nitrofurantoïne"] },
  "Fluconazole": { brands: ["Diflucan", "Mycozyde", "Mycozide", "Flucoral", "Zoltec"], aliases: ["fluconazol", "flucanzole", "mycozide", "mycozyde"] },
  "Terbinafine": { brands: ["Lamisil", "Terbizil", "Fungazol", "Daskil"], aliases: ["terbinafin", "terbinafine"] },
  "Clotrimazole": { brands: ["Canesten", "Mycelex", "Clotrimaderm", "Lotrimin"], aliases: ["clotrimazole", "clotrimazol"] },
  "Miconazole": { brands: ["Daktarin", "Monistat", "Gyno-Daktarin"], aliases: ["miconazole", "miconazol"] },
  "Nystatin": { brands: ["Mycostatine", "Nilstat", "Nystop", "Mycostatin"], aliases: ["nystatin", "nystatine"] },
  "Acyclovir": { brands: ["Zovirax", "Aciclovir", "Activir", "Herpex"], aliases: ["acyclovir", "aciclovir"] },
  "Valacyclovir": { brands: ["Zelitrex", "Valtrex", "Valcivir", "Viranet"], aliases: ["valacyclovir", "valaciclovir"] },
  "Famciclovir": { brands: ["Famvir", "Famtrex", "Oravir"], aliases: ["famciclovir"] },
  "Oseltamivir": { brands: ["Tamiflu", "Antiflu", "Fluvir"], aliases: ["oseltamivir"] },
  "Cetirizine": { brands: ["Zyrtec", "Virlix", "Reactine", "Cetir"], aliases: ["cetirizine", "cetirizina"] },
  "Loratadine": { brands: ["Clarityne", "Claritin", "Dolostop", "Lorano"], aliases: ["loratadine", "loratadina"] },
  "Fexofenadine": { brands: ["Telfast", "Allegra", "Fastofen"], aliases: ["fexofenadine", "fexofénadine"] },
  "Diphenhydramine": { brands: ["Benadryl", "Noctyl", "Nautamine", "Allerdryl"], aliases: ["diphenhydramine", "diphénhydramine"] },
  "Levocetirizine": { brands: ["Xyzall", "Xyzal", "Levocet", "Zenriz"], aliases: ["levocetirizine", "lévocetirizine"] },
  "Azelastine": { brands: ["Afluon", "Allergodil", "Rhinolast", "Optilast"], aliases: ["azelastine", "azélastine"] },
  "Ipratropium": { brands: ["Atrovent", "Ipraxa", "Aerovent", "Rinatec"], aliases: ["ipratropium"] },
  "Tiotropium": { brands: ["Spiriva", "Braltus"], aliases: ["tiotropium"] },
  "Umeclidinium": { brands: ["Incruse", "Ellipta"], aliases: ["umeclidinium"] },
  "Budesonide": { brands: ["Pulmicort", "Rhinocort", "Entocort", "Budelin"], aliases: ["budesonide", "budésonide"] },
  "Fluticasone-Salmeterol": { brands: ["Seretide", "Advair", "Viani", "AirFluSal"], aliases: ["fluticasone salmeterol", "salmeterol fluticasone"] },
  "Budesonide-Formoterol": { brands: ["Symbicort", "Duoresp", "Vannair", "Bufomix"], aliases: ["budesonide formoterol", "formoterol budesonide"] },
  "Insulin Aspart": { brands: ["NovoRapid", "NovoLog", "Fiasp"], aliases: ["insulin aspart", "insuline asparte"] },
  "Insulin Lispro": { brands: ["Humalog", "Liprolog", "Admelog"], aliases: ["insulin lispro", "insuline lispro"] },
  "Sitagliptin": { brands: ["Januvia", "Xelevia", "Ristaben", "Tesavel"], aliases: ["sitagliptin", "sitagliptine"] },
  "Linagliptin": { brands: ["Trajenta", "Tradjenta", "Ondero"], aliases: ["linagliptin", "linagliptine"] },
  "Pioglitazone": { brands: ["Actos", "Glustin", "Pioglit", "Zactos"], aliases: ["pioglitazone", "pioglitazona"] },
  "Canagliflozin": { brands: ["Invokana", "Vokanamet"], aliases: ["canagliflozin", "canagliflozine"] },
  "Dapagliflozin": { brands: ["Forxiga", "Farxiga", "Xigduo"], aliases: ["dapagliflozin", "dapagliflozine"] },
  "Ertugliflozin": { brands: ["Steglatro"], aliases: ["ertugliflozin"] },
  "Exenatide": { brands: ["Byetta", "Bydureon"], aliases: ["exenatide", "exénatide"] },
  "Liraglutide": { brands: ["Victoza", "Saxenda"], aliases: ["liraglutide"] },
  "Dulaglutide": { brands: ["Trulicity"], aliases: ["dulaglutide"] },
  "Amiodarone": { brands: ["Cordarone", "Pacerone", "Nexterone", "Aratac"], aliases: ["amiodarone", "amiodarona"] },
  "Sotalol": { brands: ["Sotalex", "Betapace", "Sotacor"], aliases: ["sotalol"] },
  "Verapamil": { brands: ["Isoptine", "Calan", "Verelan", "Cordilox"], aliases: ["verapamil", "vérapamil"] },
  "Diltiazem": { brands: ["Tildiem", "Cardizem", "Dilzem"], aliases: ["diltiazem"] },
  "Hydralazine": { brands: ["Nepressol", "Apresoline"], aliases: ["hydralazine", "hydralazina"] },
  "Isosorbide Dinitrate": { brands: ["Risordan", "Isordil", "Cedocard", "Isoket"], aliases: ["isosorbide dinitrate", "ISDN"] },
  "Nitroprusside": { brands: ["Nipride", "Nitropress"], aliases: ["nitroprusside", "sodium nitroprusside"] },
  "Prasugrel": { brands: ["Efient", "Effient"], aliases: ["prasugrel"] },
  "Ticagrelor": { brands: ["Brilique", "Brilinta"], aliases: ["ticagrelor"] },
  "Edoxaban": { brands: ["Lixiana", "Savaysa"], aliases: ["edoxaban", "edoxabane"] },
  "Dabigatran": { brands: ["Pradaxa"], aliases: ["dabigatran"] },
  "Heparin": { brands: ["Heparine", "Calciparine", "Liquemine"], aliases: ["heparin", "héparine"] },
  "Enoxaparin": { brands: ["Lovenox", "Clexane", "Inhixa"], aliases: ["enoxaparin", "énoxaparine"] },
  "Fondaparinux": { brands: ["Arixtra"], aliases: ["fondaparinux"] },
  "Alteplase": { brands: ["Actilyse", "Activase"], aliases: ["alteplase", "tPA"] },
  "Tenecteplase": { brands: ["Metalyse", "TNKase"], aliases: ["tenecteplase", "TNK"] },
  "Reteplase": { brands: ["Rapilysin", "Retavase"], aliases: ["reteplase"] },
  "Amoxicillin-Clavulanate": { brands: ["Augmentin", "Claventin", "Amoclav", "Bactoclav"], aliases: ["amoxiclav", "amoxicilline acide clavulanique", "co-amoxiclav"] },
  "Cefoxitin": { brands: ["Mefoxin"], aliases: ["cefoxitin", "cefoxitine"] },
  "Ceftriaxone": { brands: ["Rocephin", "Biotrakson", "Ceftriax", "Triaxon"], aliases: ["ceftriaxone", "ceftriaxon"] },
  "Cefepime": { brands: ["Maxipime"], aliases: ["cefepime", "cefépime"] },
  "Meropenem": { brands: ["Meronem", "Merrem"], aliases: ["meropenem", "méropénème"] },
  "Imipenem-Cilastatin": { brands: ["Tienam", "Primaxin"], aliases: ["imipenem cilastatin", "imipenem"] },
  "Vancomycin": { brands: ["Vancocin", "Edicin", "Lyphocin"], aliases: ["vancomycin", "vancomycine"] },
  "Linezolid": { brands: ["Zyvox", "Zyvoxid", "Zyvoxam"], aliases: ["linezolid", "linézolide"] },
  "Daptomycin": { brands: ["Cubicin"], aliases: ["daptomycin", "daptomycine"] },
  "Gentamicin": { brands: ["Gentalline", "Garamycin", "Cidomycin", "Genticin"], aliases: ["gentamicin", "gentamicine"] },
  "Tobramycin": { brands: ["Nebcin", "Tobrex", "Bramitob", "Tobi"], aliases: ["tobramycin", "tobramycine"] },
  "Cefazolin": { brands: ["Kefzol", "Ancef"], aliases: ["cefazolin", "céfazoline"] },
  "Cefuroxime": { brands: ["Zinnat", "Ceftin", "Zinacef", "Curoxime"], aliases: ["cefuroxime", "céfuroxime"] },
  "Clarithromycin": { brands: ["Klacid", "Biaxin", "Klaricid", "Fromilid"], aliases: ["clarithromycine", "claritromicina"] },
  "Erythromycin": { brands: ["Erythrocine", "Abboticin", "Ery-Tab", "Erythroped"], aliases: ["erythromycin", "érythromycine"] },
  "Aztreonam": { brands: ["Azactam", "Cayston"], aliases: ["aztreonam", "aztréonam"] },
  "Polymyxin B": { brands: ["Poly-Rx"], aliases: ["polymyxin B", "polymyxine B"] },
  "Colistin": { brands: ["Colimycine", "Colomycin", "Colistimethate"], aliases: ["colistin", "colistine", "polymyxin E"] },
  "Metronidazole": { brands: ["Flagyl", "Metrogyl", "Rozex", "Deflamon"], aliases: ["metronidazol", "métronidazole"] },
  "Tinidazole": { brands: ["Fasigyne", "Tindamax", "Simplotan"], aliases: ["tinidazole", "tinidazol"] },
  "Chloramphenicol": { brands: ["Chloromycetin", "Kemicetine"], aliases: ["chloramphenicol", "chloramphénicol"] },
  "Rifampin": { brands: ["Rifadine", "Rimactan", "Rifadin"], aliases: ["rifampin", "rifampicin", "rifampicine"] },
  "Isoniazid": { brands: ["Rimifon", "Nydrazid"], aliases: ["isoniazid", "isoniazide", "INH"] },
  "Pyrazinamide": { brands: ["Pirilene", "Rifater"], aliases: ["pyrazinamide", "PZA"] },
  "Ethambutol": { brands: ["Myambutol", "Dexambutol"], aliases: ["ethambutol", "EMB"] },
  "Moxifloxacin": { brands: ["Izilox", "Avelox", "Avalox", "Vigamox"], aliases: ["moxifloxacin", "moxifloxacine"] },
  "Ofloxacin": { brands: ["Oflocet", "Floxin", "Ocuflox", "Tarivid"], aliases: ["ofloxacin", "ofloxacine"] },
  "Hydroxychloroquine": { brands: ["Plaquenil", "Quensyl"], aliases: ["hydroxychloroquine", "HCQ"] },
  "Leflunomide": { brands: ["Arava", "Lunava"], aliases: ["leflunomide", "léflunomide"] },
  "Sulfasalazine": { brands: ["Salazopyrin", "Azulfidine", "Sulazine"], aliases: ["sulfasalazine"] },
  "Etanercept": { brands: ["Enbrel", "Benepali", "Erelzi"], aliases: ["etanercept"] },
  "Adalimumab": { brands: ["Humira", "Amgevita", "Hyrimoz", "Hadlima"], aliases: ["adalimumab"] },
  "Infliximab": { brands: ["Remicade", "Remsima", "Inflectra", "Flixabi"], aliases: ["infliximab"] },
  "Golimumab": { brands: ["Simponi", "Simponi Aria"], aliases: ["golimumab"] },
  "Certolizumab": { brands: ["Cimzia"], aliases: ["certolizumab", "certolizumab pegol"] },
  "Tofacitinib": { brands: ["Xeljanz"], aliases: ["tofacitinib"] },
  "Baricitinib": { brands: ["Olumiant"], aliases: ["baricitinib"] },
  "Abatacept": { brands: ["Orencia"], aliases: ["abatacept"] },
  "Rituximab": { brands: ["Mabthera", "Rituxan", "Rixathon"], aliases: ["rituximab"] },
  "Tocilizumab": { brands: ["Roactemra", "Actemra"], aliases: ["tocilizumab"] },
  "Anakinra": { brands: ["Kineret"], aliases: ["anakinra"] },
  "Secukinumab": { brands: ["Cosentyx"], aliases: ["secukinumab"] },
  "Ustekinumab": { brands: ["Stelara"], aliases: ["ustekinumab"] },
  "Ixekizumab": { brands: ["Taltz"], aliases: ["ixekizumab"] },
  "Brodalumab": { brands: ["Kyntheum", "Siliq"], aliases: ["brodalumab"] },
  "Dupilumab": { brands: ["Dupixent"], aliases: ["dupilumab"] },
  "Omalizumab": { brands: ["Xolair"], aliases: ["omalizumab"] },
  "Mepolizumab": { brands: ["Nucala"], aliases: ["mepolizumab"] },
  "Reslizumab": { brands: ["Cinqaero", "Cinqair"], aliases: ["reslizumab"] },
  "Benralizumab": { brands: ["Fasenra"], aliases: ["benralizumab"] },
  "Tralokinumab": { brands: ["Adtralza"], aliases: ["tralokinumab"] },
  "Fevipiprant": { brands: ["Winrevair"], aliases: ["fevipiprant"] },
  "Olopatadine": { brands: ["Opatanol", "Pataday", "Patanol", "Oloptec"], aliases: ["olopatadine"] },
  "Ketotifen": { brands: ["Zaditen", "Ketof", "Zaditene"], aliases: ["ketotifen", "kétotifène"] },
  "Zafirlukast": { brands: ["Accolate", "Vanticon"], aliases: ["zafirlukast"] },
  "Theophylline": { brands: ["Théostat", "Theodur", "Uniphyl", "Nuelin"], aliases: ["theophylline", "théophylline"] },
  "Salmeterol": { brands: ["Serevent", "Asmadil"], aliases: ["salmeterol", "salmétérol"] },
  "Formoterol": { brands: ["Foradil", "Atimos", "Oxeze"], aliases: ["formoterol", "formotérol"] },
  "Vilanterol": { brands: ["Anoro", "Relvar", "Breo"], aliases: ["vilanterol"] },
  "Indacaterol": { brands: ["Onbrez", "Arcapta", "Oslif"], aliases: ["indacaterol"] },
  "Olodaterol": { brands: ["Striverdi", "Spiolto"], aliases: ["olodaterol"] },
  "Ciclesonide": { brands: ["Alvesco", "Omnaris", "Zetonna"], aliases: ["ciclesonide"] },
  "Beclomethasone": { brands: ["Becotide", "Qvar", "Clenil", "Beconase"], aliases: ["beclomethasone", "béclométhasone"] },
  "Flunisolide": { brands: ["Syntaris", "Aerobid", "Aerospan"], aliases: ["flunisolide"] },
  "Mometasone-Formoterol": { brands: ["Dulera", "Inspiolto"], aliases: ["mometasone formoterol"] },
  "Tiotropium-Olodaterol": { brands: ["Spiolto", "Stiolto"], aliases: ["tiotropium olodaterol"] },
  "Umeclidinium-Vilanterol": { brands: ["Anoro Ellipta"], aliases: ["umeclidinium vilanterol"] },
  "Albuterol-Ipratropium": { brands: ["Combivent", "Duovent", "Ipramol"], aliases: ["salbutamol ipratropium", "albuterol ipratropium"] },
  "Levalbuterol": { brands: ["Xopenex"], aliases: ["levalbuterol", "levosalbutamol"] },
  "Terbutaline": { brands: ["Bricanyl", "Brethine", "Terbasmin"], aliases: ["terbutaline", "terbutalina"] },
  "Roflumilast": { brands: ["Daxas", "Daliresp"], aliases: ["roflumilast"] },
  "Zileuton": { brands: ["Zyflo", "Zyflo CR"], aliases: ["zileuton"] },
}

// Extra medications not in the original list.json — add more here as you discover them
const extraMedications = [
  {
    name: "Tetracycline",
    common_abbreviation: "TCN",
    brands: ["Tetracyne", "Achromycin", "Steclin", "Hostacycline"],
    aliases: ["tetracycline", "tétracycline"],
    category: "antibiotic",
    sub_category: "tetracycline",
    dosage_forms: ["capsule", "tablet", "ointment"],
    common_doses: ["250mg", "500mg"],
    notes: "Broad spectrum antibiotic",
  },
  {
    name: "Thiocolchicoside",
    common_abbreviation: "TCC",
    brands: ["Tatioflex", "Miorel", "Coltramyl", "Thiocolchicosid"],
    aliases: ["thiocolchicoside", "tatioflex", "coltramyl"],
    category: "muscle relaxant",
    sub_category: "skeletal muscle relaxant",
    dosage_forms: ["tablet", "injection", "gel"],
    common_doses: ["4mg", "8mg"],
    notes: "Muscle relaxant and antispasmodic",
  },
  {
    name: "Albesyrex",
    common_abbreviation: "ALB",
    brands: ["Albesyrex"],
    aliases: ["albesyrex", "albésyrex"],
    category: "antibiotic",
    sub_category: "quinolone",
    dosage_forms: ["tablet", "syrup"],
    common_doses: ["200mg", "400mg"],
    notes: "Algerian brand — pefloxacin antibiotic",
  },
]


  try {
    await mongoose.connect(process.env.MONGO_URI)
    console.log("✅ Connected to MongoDB")

    const original = JSON.parse(fs.readFileSync("./list.json", "utf8"))

    const enriched = original.map(med => ({
      ...med,
      brands: enrichmentData[med.name]?.brands || [],
      aliases: enrichmentData[med.name]?.aliases || [],
    }))

    await MED.deleteMany({})
    console.log("🗑️  Cleared existing medications")

    await MED.insertMany([...enriched, ...extraMedications])

    const total = enriched.length + extraMedications.length
    const withBrands = [...enriched, ...extraMedications].filter(m => m.brands.length > 0).length
    console.log(`✅ Inserted ${total} medications (${enriched.length} from list + ${extraMedications.length} extra)`)
    console.log(`📊 ${withBrands}/${total} have brand names`)

    mongoose.connection.close()
    console.log("🎉 Seed complete!")
  } catch (error) {
    console.error("❌ Seed failed:", error.message)
    process.exit(1)
  }

  

seed()